#### Alarm Config
### 해당 파일은 CCTV 알람을 설정하는 파일입니다.
## 양식은 이하와 같습니다. ( {} 안의 값은 실제 값을 의미)
#
# [{알람 이름}]
# target_channel : 해당 alarm이 어느 채널에서의 알람인지
# risk_level : {위험 정도}
# Alarm Sentence : (알람에 적힐 context)
# {class1} and {class2} and {class3}
# (not {class1} or {class2}) and not {class3}
# ({class3} and {class4}) or ({class2} and {class5})
# [/{알람이름}]
# 
# and, or, not 옆엔 공백이 있어야 합니다.
# not {class1} : class1이 탐지되지 않을 경우
# {class1} and {class2} : class1 과 class2가 탐지될 경우
# {class1} or {class2} : class1 혹은 class2가 탐지될 경우
#
## class 설명
#
# 0  : standing
# 1  : lying down on bed
# 2  : sitting on bed
# 3  : fallen down
# 4  : wheel chair
# 5  : unknown status
# 6  : sitting on chair
# 7  : sitting on the floor
# 8  : food tray
# 9  : perch on bed
# 10 : staff
#
## (아래부터는 실제 설정을 입력해주세요)

[alarm1]
target_channel : 1
alarm_id : 1
Alarm Sentence : staff 탐지 (디버깅용 알람입니다.)
0

[alarm2]
target_channel : 2
alarm_id : 1
Alarm Sentence : debug
0


# [alarm3]
# risk_level : 2
# 0 and 1

#[alarm4]
#risk_level : 5
#(0 and 1) or (not 1 and 2 and 3)

#[alarm5]
#risk_level : 6
#((0 or 1) and 2)
